version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/shopgular-backend"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/shopgular-frontend"
    schedule:
      interval: "daily"
