version: "3.9"
services:
  mysqldb:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: unless-stopped
    ports:
      - $NEXUS_LOCAL_PORT:$NEXUS_DOCKER_PORT
  sonarqube:
    image: sonarqube:8.9.7-community
    container_name: sonarqube
    restart: unless-stopped
    ports:
      - $SONARQUBE_LOCAL_PORT:$SONARQUBE_DOCKER_PORT
  shopgular-backend:
    image: shopgular-backend:0.1.0
    container_name: shopgular-backend
    restart: on-failure
    ports:
      - $SHOPGULAR_BACKEND_LOCAL_PORT:$SHOPGULAR_BACKEND_DOCKER_PORT
    environment:
      spring_application_json: '{ "spring.datasource.url": "jdbc:mysql://mysqldb/shopgular?createDatabaseIfNotExist=true" }'
    build: .
    depends_on:
      - mysqldb
