pipeline {
    environment {
        IMAGE = ""
        WORKDIR = "shopgular-backend"
        REGISTRY = "aminous/shopgular"
        VERSION = "backend-2.0.0-$BUILD_NUMBER"
        RECIPIENT = "mohamedamine.benfredj1@esprit.tn"
    }
    agent any
    options { timestamps() }
    tools { maven 'MAVEN_HOME' }
    stages {
        stage('Sending email') {
            steps {
                emailext(
                    attachLog: true,
                    body: 'You received this email because we have detected a new build job from Jenkins. Please refer to the attachment below for more details. \n\nRegards, \nThe Shopgular Team',
                    subject: '[Jenkins Pipeline]',
                    to: RECIPIENT
                )
            }
        }
        stage('Cloning repository') {
            steps {
                git branch: 'master', credentialsId: 'shopgular-git', url: 'https://github.com/amin-ous/shopgular.git'
            }
        }
        stage('Initializing application') {
            steps {
                dir(WORKDIR) {
                    sh 'mvn clean install -DskipTests'
                }
            }
        }
        stage('Testing application') {
            steps {
                dir(WORKDIR) {
                    sh 'mvn test jacoco:report'
                }
            }
        }
        stage('Checking code quality') {
            steps {
                dir(WORKDIR) {
                    sh 'mvn sonar:sonar -Dsonar.login=admin -Dsonar.password=shopgular'
                }
            }
        }
        stage('Deploying artifact') {
            steps {
                dir(WORKDIR) {
                    sh 'mvn deploy -DskipTests'
                }
            }
        }
        stage('Building image') {
            steps {
                dir(WORKDIR) {
                    script {
                        IMAGE = docker.build REGISTRY + ":$VERSION"
                    }
                }
            }
        }
        stage('Deploying image') {
            steps {
                dir(WORKDIR) {
                    script {
                        docker.withRegistry('', 'shopgular-docker') {
                            IMAGE.push()
                        }
                    }
                }
            }
        }
        stage('Cleaning up') {
            steps {
                dir(WORKDIR) {
                    sh "docker rmi $REGISTRY:$VERSION"
                }
            }
        }
    }
}
